import type { Metadata } from "next";
import {Inter, Poppins} from "next/font/google";
import "../globals.css";
import Header from "@/components/header/Header";
import {ClerkProvider} from "@clerk/nextjs"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider> 
    <html lang="en">
      <body
className={`${inter.variable} ${poppins.variable}`}
      >
        <Header/>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
